function empty(e){var t,n,r,i;var s=[t,null,false,0,"","0"];for(r=0,i=s.length;r<i;r++){if(e===s[r]){return true}}if(typeof e==="object"){for(n in e){return false}return true}return false}
function ucwords(e){return(e+"").replace(/^([a-z\u00E0-\u00FC])|\s+([a-z\u00E0-\u00FC])/g,function(e){return e.toUpperCase()})}
function in_array(e,t,n){var r="",i=!!n;if(i){for(r in t){if(t[r]===e){return true}}}else{for(r in t){if(t[r]==e){return true}}}return false}
function is_numeric(e){var t=" \n\r\t\f\x0b\xa0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000";return(typeof e==='number'||(typeof e==='string'&&t.indexOf(e.slice(-1))===-1))&&e!==''&&!isNaN(e)}
function implode(e,t){var n="",r="",i="";if(arguments.length===1){t=e;e=""}if(typeof t==="object"){if(Object.prototype.toString.call(t)==="[object Array]"){return t.join(e)}for(n in t){r+=i+t[n];i=e}return r}return t}
function strip_tags(e,t){t=(((t||"")+"").toLowerCase().match(/<[a-z][a-z0-9]*>/g)||[]).join("");var n=/<\/?([a-z][a-z0-9]*)\b[^>]*>/gi,r=/<!--[\s\S]*?-->|<\?(?:php)?[\s\S]*?\?>/gi;return e.replace(r,"").replace(n,function(e,n){return t.indexOf("<"+n.toLowerCase()+">")>-1?e:""})}
function ucfirst(e){e+="";var t=e.charAt(0).toUpperCase();return t+e.substr(1)}
function array_search(e,t,n){var r=!!n,i="";if(t&&typeof t==="object"&&t.change_key_case){return t.search(e,n)}if(typeof e==="object"&&e.exec){if(!r){var s="i"+(e.global?"g":"")+(e.multiline?"m":"")+(e.sticky?"y":"");e=new RegExp(e.source,s)}for(i in t){if(e.test(t[i])){return i}}return false}for(i in t){if(r&&t[i]===e||!r&&t[i]==e){return i}}return false}
function trim(a,b){var c,d=0,e=0;for(a+="",b?(b+="",c=b.replace(/([\[\]\(\)\.\?\/\*\{\}\+\$\^\:])/g,"$1")):c=" \n\r	\f\xa0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000",d=a.length,e=0;d>e;e++)if(-1===c.indexOf(a.charAt(e))){a=a.substring(e);break;}for(d=a.length,e=d-1;e>=0;e--)if(-1===c.indexOf(a.charAt(e))){a=a.substring(0,e+1);break;}return-1===c.indexOf(a.charAt(0))?a:""}
function str_replace(a,b,c,d){var e=0,f=0,g="",h="",i=0,j=0,k=[].concat(a),l=[].concat(b),m=c,n="[object Array]"===Object.prototype.toString.call(l),o="[object Array]"===Object.prototype.toString.call(m);for(m=[].concat(m),d&&(this.window[d]=0),e=0,i=m.length;i>e;e++)if(""!==m[e])for(f=0,j=k.length;j>f;f++)g=m[e]+"",h=n?void 0!==l[f]?l[f]:"":l[0],m[e]=g.split(k[f]).join(h),d&&m[e]!==g&&(this.window[d]+=(g.length-m[e].length)/k[f].length);return o?m:m[0]}
function stripos(a,b,d){a=(a+"").toLowerCase();b=(b+"").toLowerCase();var c=0;return-1!==(c=a.indexOf(b,d))?c:!1}
function explode(a,d,b){if(2>arguments.length||"undefined"===typeof a||"undefined"===typeof d)return null;if(""===a||!1===a||null===a)return!1;if("function"===typeof a||"object"===typeof a||"function"===typeof d||"object"===typeof d)return{0:""};!0===a&&(a="1");a+="";var c=(d+"").split(a);if("undefined"===typeof b)return c;0===b&&(b=1);if(0<b)return b>=c.length?c:c.slice(0,b-1).concat([c.slice(b-1).join(a)]);if(-b>=c.length)return[];c.splice(c.length+b);return c}
function is_array(a){var b,c=function(a){var b=/\W*function\s+([\w\$]+)\s*\(/.exec(a);return b?b[1]:"(Anonymous)"};return _isArray=function(a){if(!a||"object"!=typeof a||"number"!=typeof a.length)return!1;var b=a.length;return a[a.length]="bogus",b!==a.length?(a.length-=1,!0):(delete a[a.length],!1)},a&&"object"==typeof a?(this.php_js=this.php_js||{},this.php_js.ini=this.php_js.ini||{},b=this.php_js.ini["phpjs.objectsAsArrays"],_isArray(a)||(!b||0!==parseInt(b.local_value,10)&&(!b.local_value.toLowerCase||"off"!==b.local_value.toLowerCase()))&&"[object Object]"===Object.prototype.toString.call(a)&&"Object"===c(a.constructor)):!1}
function is_object(a){return"[object Array]"===Object.prototype.toString.call(a)?!1:null!==a&&"object"==typeof a}
function strpos(a,b,c){var d=(a+"").indexOf(b,c||0);return-1===d?!1:d}
function urldecode(e){return decodeURIComponent((e+"").replace(/%(?![\da-f]{2})/gi,function(){return"%25"}).replace(/\+/g,"%20"))}
function floor(o){return Math.floor(o)}
function ceil(o){return Math.ceil(o)}
function str_pad(_,T,r,t){var R,n="",A=function(_,T){for(var r="";r.length<T;)r+=_;return r=r.substr(0,T)};return _+="",r=void 0!==r?r:" ","STR_PAD_LEFT"!==t&&"STR_PAD_RIGHT"!==t&&"STR_PAD_BOTH"!==t&&(t="STR_PAD_RIGHT"),(R=T-_.length)>0&&("STR_PAD_LEFT"===t?_=A(r,R)+_:"STR_PAD_RIGHT"===t?_+=A(r,R):"STR_PAD_BOTH"===t&&(n=A(r,Math.ceil(R/2)),_=n+_+n,_=_.substr(0,T))),_}
function nl2br(r,n){var e=n||"undefined"==typeof n?"<br />":"<br>";return(r+"").replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,"$1"+e+"$2")}